### ISSUE TITLE
User Story: Index

### ISSUE THREAD

**Issue by gregkorte** [nss-alumni/hackathon1-team06#1]
# Story

As a user, when I land on the index page I will see the splash page.

# Acceptance Criteria

**Given** the user first arrives at the index
**Then** the splash page will be able to be viewed

# Technical Information

1. Create the index view

# Related Tickets

**Comment by jevonthomas** [comment]
- [ ] Structure the index file to support angular materialize and angular route

- [ ] Set a route for the index page in app.js

- [ ] Create an index partial

- [ ] Create an index controller
